name = "rectangle_stack"

[stack]
count = 15
spacing = { x = 0.0, y = 4.2, z = 0.0 }
start_offset = { x = 0.0, y = 0.2, z = 0.0 }

[overrides.physics]
restitution = 0.05
friction = 0.9

[[parts]]
template = "entities/rectangle.3D.toml"
name_override = "stack_rect"
