# Menu input configuration

[camera]
mode = "2d"
[camera.movement]
control = "mouse"
speed = 0.0
forward = ""
backward = ""
left = ""
right = ""

[camera.rotation]
degrees_per_second = 0.0
yaw_left = ""
yaw_right = ""
pitch_up = ""
pitch_down = ""

[[overlays]]
name = "menu"
toggle = ""
